### PR TITLE
reset stdin/out/err when reloading sys

### LINKED ISSUE #567: output abnormal after reload(sys)
```
>>> import sys
>>> id(sys)
4545665968
>>> reload(sys)
>>> id(sys)
>>> 
```

bpython output is missing or abnormal. I've tested that original Python shell or IPython, both of them work fine.

### PR DESCRIPTION
**Pull request by thomasballinger**
fixes #567

### CODE REVIEW

**Comment by sebastinas** [comment]
The code does not work:
```py
bpython version 0.15.dev127 on top of Python 3.4.4 /usr/bin/python3
>>> import Crypto
>>> import importlib
>>> importlib.reload(Crypto)
Traceback (most recent call last):
  File "<bpython-input-4>", line 1, in <module>
    importlib.reload(Crypto)
  File "/home/sebastian/development/bpython/bpython/curtsiesfrontend/sitefix.py", line 42, in reload
    builtins.reload(sys)
AttributeError: 'module' object has no attribute 'reload'
```

**Comment by thomasballinger** [comment]
* correctly finds reload on Python 3.3
* adds tests that new reload works
* only does the monkeypatch on Python 2 because sys.stdout isn't replaced on `reload(sys)` in Python 3

**Comment by thomasballinger** [comment]
I'd like to merge or close this soon. I'm happy with it now, and although it's a lot of code, the monkeypatching of reload only happens in Python 2 so we're mostly adding cruft to old Python. I don't understand how useful the use case is, see https://github.com/bpython/bpython/issues/567#issuecomment-166774548 for rationale.

**Comment by sebastinas** [comment]
I'm not sure about this, but if you want it for 0.16, please merge it soon.

**Comment by thomasballinger** [comment]
It's just adding cruft.

**Pull request closed without merging**
