### PR TITLE
WIP - width aware output take 2

### PR DESCRIPTION
**Pull request by thomasballinger**
The Curtsies version referenced does not exist yet, don't merge.

Perf looks better now, a linear 10x slower. Wonder if this is good enough, I made some guesses about how to make things fast in https://github.com/bpython/curtsies/pull/109 but haven't profiled at all.

betterperf

### CODE REVIEW

**Comment by thomasballinger** [comment]
A requirement for merging this should be identifying exactly what it's fixing. I had thought it might be fixing issues like #670 but that has to do with terminal escapes - this is really only a unicode fix.

**Comment by thomasballinger** [comment]
Another issue: `print('a\tsdf'*100)` crashes with this patch applied (previously how did this work?)

**Comment by ikanobori** [comment]
Not entirely sure but could you, while you're in this part of the code, see if this also gets resolved: https://github.com/bpython/bpython/issues/724 with the patches?

**Comment by thomasballinger** [comment]
@rybarczykj knows where this is if we work on this more, I'm closing because even if we do this it won't be with this PR.

**Pull request closed without merging**
