### PR TITLE
add typing-extensions requirement

### LINKED ISSUE #938: missing typing_extensions dependency in 0.22 release
```
# bpython
Traceback (most recent call last):
  File "/usr/local/bin/bpython", line 5, in <module>
    from bpython.curtsies import main
  File "/usr/local/lib/python3.10/site-packages/bpython/curtsies.py", line 16, in <module>
    from . import args as bpargs, translations, inspection
  File "/usr/local/lib/python3.10/site-packages/bpython/args.py", line 47, in <module>
    from .config import default_config_path, Config
  File "/usr/local/lib/python3.10/site-packages/bpython/config.py", line 37, in <module>
    from .autocomplete import AutocompleteModes
  File "/usr/local/lib/python3.10/site-packages/bpython/autocomplete.py", line 50, in <module>
    from . import inspection
  File "/usr/local/lib/python3.10/site-packages/bpython/inspection.py", line 31, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

### PR DESCRIPTION
**Pull request by dtrodrigues**
resolves #938

### CODE REVIEW

**Comment by sebastinas** [comment]
Thank you. I've rebased and merged your PR on the `0.22-bufix` branch. In `main`, we can get rid of `typing_extensions` since Python 3.6 support was removed.

**Comment by sebastinas** [comment]
Ah, that won't work. `Literal` was only added in 3.8.

**Comment by thomasballinger** [comment]
oof, sorry about introducing Literal, I should have left it as bool or whatever

**Comment by sebastinas** [comment]
For `__exit__`, `Literal[False]` is actually recommended. So it's fine. 0.22.1 has been released to add the dependency on `typeing_extensions`.

**Pull request closed without merging**
